### ISSUE TITLE
Error handling notification for interface

### ISSUE THREAD

**Issue by gspe** [craftyguy/networkd-dispatcher#22]
I'm trying to setup some script to use with systemd-networkd when executed I get this error:
```
giu 16 15:07:12 jura networkd-dispatcher[4251]: ERROR:Error handling notification for interface 'eno1' entering state routable
giu 16 15:07:12 jura networkd-dispatcher[4251]: Traceback (most recent call last):
giu 16 15:07:12 jura networkd-dispatcher[4251]:   File "/usr/bin/networkd-dispatcher", line 252, in _receive_signal
giu 16 15:07:12 jura networkd-dispatcher[4251]:     self.handle_state(iface_name, str(state))
giu 16 15:07:12 jura networkd-dispatcher[4251]:   File "/usr/bin/networkd-dispatcher", line 220, in handle_state
giu 16 15:07:12 jura networkd-dispatcher[4251]:     ret = subprocess.Popen(script, env=script_env).wait()
giu 16 15:07:12 jura networkd-dispatcher[4251]:   File "/usr/lib/python3.6/subprocess.py", line 707, in __init__
giu 16 15:07:12 jura networkd-dispatcher[4251]:     restore_signals, start_new_session)
giu 16 15:07:12 jura networkd-dispatcher[4251]:   File "/usr/lib/python3.6/subprocess.py", line 1326, in _execute_child
giu 16 15:07:12 jura networkd-dispatcher[4251]:     raise child_exception_type(errno_num, err_msg)
giu 16 15:07:12 jura networkd-dispatcher[4251]: OSError: [Errno 8] Exec format error
```

**Comment by craftyguy** [comment]
That seems to indicate that the file you are trying to execute is not executable. Is that true? If it's a shell script, you need to also define the interpreter on the first line (e.g. !#/bin/bash)

**Comment by charles-dyfis-net** [comment]
I think that one's not so much "not executable" as "not executable on the current architecture" (ie. built for a different platform).

**Comment by craftyguy** [comment]
Ah, good catch. That'll do it too :P

**Comment by charles-dyfis-net** [comment]
This does mean it's got the executable bit set -- but might not have a shebang, or might be a binary compiled for a different architecture.

**Comment by gspe** [comment]
Thanks for fast reply, I managed to solve the problem.
I don't know why but the first line was a blank line instead of shebang!
