### ISSUE TITLE
using iw crashes networkd-dispatcher

### ISSUE THREAD

**Issue by tekdoc** [craftyguy/networkd-dispatcher#28]
I am using iw rather than iwconfig as the configuration utility for my wireless NIC.  The fact that iwconfig is absent from my system seems to crash networkd-dispatcher:

```
patcher[161]: wlan0     no wireless extensions.
patcher[161]: ERROR:Error handling notification for interface 'wlan0' entering operational state routable
patcher[161]: Traceback (most recent call last):
patcher[161]:   File "/usr/bin/networkd-dispatcher", line 208, in _handle_one_state
patcher[161]:     self.run_hooks_for_state(new_iface, state)
patcher[161]:   File "/usr/bin/networkd-dispatcher", line 225, in run_hooks_for_state
patcher[161]:     data = get_interface_data(iface, state)
patcher[161]:   File "/usr/bin/networkd-dispatcher", line 139, in get_interface_data
patcher[161]:     data['ESSID'] = get_wlan_essid(iface.name)
patcher[161]:   File "/usr/bin/networkd-dispatcher", line 94, in get_wlan_essid
patcher[161]:     out = subprocess.check_output([IWCONFIG, '--', iface_name])
patcher[161]:   File "/usr/lib/python3.6/subprocess.py", line 336, in check_output
patcher[161]:     **kwargs).stdout
patcher[161]:   File "/usr/lib/python3.6/subprocess.py", line 418, in run
patcher[161]:     output=stdout, stderr=stderr)
patcher[161]: subprocess.CalledProcessError: Command '['/usr/bin/iwconfig', '--', 'wlan0']' returned non-zero 
```
It would be nice to get networkd-dispatcher working with iw since iwconfig is now deprecated.  Otherwise, great work on this app!

**Comment by craftyguy** [comment]
That's an excellent point about iwconfig's deprecation. I'll see what I can do to add support for iw!

**Comment by craftyguy** [comment]
@tekdoc I've implemented this in a separate branch and would really appreciate it if you could test it out (see the [feature/add_iw_support](https://github.com/craftyguy/networkd-dispatcher/tree/feature/add_iw_support) branch). If not, I *think* I have tested it reasonably well on Arch Linux.

**Comment by tekdoc** [comment]
I'm getting an error when I try to run it:

```
  File "/usr/bin/networkd-dispatcher", line 110
    logger.('Unable to retrieve ESSID for wireless interface %r.')
           ^
SyntaxError: invalid syntax
```

**Comment by craftyguy** [comment]
Well that was embarassing. Sorry, it's fixed now!

**Comment by tekdoc** [comment]
Syntax error is gone but still getting this:

```
wlan0     no wireless extensions.

ERROR:Error handling notification for interface 'wlan0' entering operational state routable
Traceback (most recent call last):
  File "/usr/bin/networkd-dispatcher", line 211, in _handle_one_state
    self.run_hooks_for_state(new_iface, state)
  File "/usr/bin/networkd-dispatcher", line 228, in run_hooks_for_state
    data = get_interface_data(iface, state)
  File "/usr/bin/networkd-dispatcher", line 142, in get_interface_data
    data['ESSID'] = get_wlan_essid(iface.name)
  File "/usr/bin/networkd-dispatcher", line 94, in get_wlan_essid
    out = subprocess.check_output([IWCONFIG, '--', iface_name])
  File "/usr/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/usr/bin/iwconfig', '--', 'wlan0']' returned non-zero exit status 161.
```

**Comment by tekdoc** [comment]
Syntax error is gone but I am still getting this:

```
wlan0     no wireless extensions.

ERROR:Error handling notification for interface 'wlan0' entering operational state routable
Traceback (most recent call last):
  File "/usr/bin/networkd-dispatcher", line 235, in _handle_one_state
    self.run_hooks_for_state(new_iface, state)
  File "/usr/bin/networkd-dispatcher", line 252, in run_hooks_for_state
    data = get_interface_data(iface, state)
  File "/usr/bin/networkd-dispatcher", line 166, in get_interface_data
    data['ESSID'] = get_wlan_essid(iface.name)
  File "/usr/bin/networkd-dispatcher", line 102, in get_wlan_essid
    return iwconfig_get_ssid(iface_name)
  File "/usr/bin/networkd-dispatcher", line 117, in iwconfig_get_ssid
    out = subprocess.check_output([IWCONFIG, '--', iface_name])
  File "/usr/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/usr/bin/iwconfig', '--', 'wlan0']' returned non-zero exit status 161.
```

**Comment by craftyguy** [comment]
Hmm, do you have iwconfig installed? It shouldn't run iwconfig_get_ssid unless it was able to find a valid path to the `iwconfig` exe

**Comment by tekdoc** [comment]
Yep, that was it. I had installed the wireless_tools package when I was using a different device driver. The current one doesn't use it.  Removed the package and everything seems to be working now. Thanks!

**Comment by craftyguy** [comment]
Great to hear! I'll go ahead and merge this change then. Thanks for reporting and testing, I really appreciate it :+1:
